"""empty message

Revision ID: 05f661d0e53f
Revises: 7dba047fdf1e
Create Date: 2024-09-04 22:56:12.554706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f661d0e53f'
down_revision = '7dba047fdf1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation', sa.String(length=20), nullable=False))
        batch_op.drop_column('link')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registrationt', sa.String(length=200), nullable=False))
        batch_op.drop_column('address')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_column('address')
        batch_op.drop_column('state')

    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_appointment', sa.Integer(), nullable=False))
        batch_op.drop_constraint('record_id_patient_fkey', type_='foreignkey')
        batch_op.drop_constraint('record_id_doctor_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'appointment', ['id_appointment'], ['id'])
        batch_op.drop_column('id_doctor')
        batch_op.drop_column('id_patient')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_patient', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_doctor', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('record_id_doctor_fkey', 'doctor', ['id_doctor'], ['id'])
        batch_op.create_foreign_key('record_id_patient_fkey', 'patient', ['id_patient'], ['id'])
        batch_op.drop_column('id_appointment')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('registrationt')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('confirmation')

    # ### end Alembic commands ###
