"""empty message

Revision ID: 41eb3327b5e0
Revises: 7586e9b4366e
Create Date: 2024-09-04 17:27:43.439330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41eb3327b5e0'
down_revision = '7586e9b4366e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password2', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password2')

    # ### end Alembic commands ###
