"""empty message

Revision ID: 90136f0f49fb
Revises: 6792717ad20e
Create Date: 2024-09-04 17:40:47.985477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90136f0f49fb'
down_revision = '6792717ad20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('link', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('id_doctor', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_doctor'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['id_patient'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.String(length=1000), nullable=False),
    sa.Column('recommendations', sa.String(length=1000), nullable=False),
    sa.Column('treatment', sa.String(length=1000), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('id_doctor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_doctor'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['id_patient'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('appointment')
    # ### end Alembic commands ###
